library(tidyverse)
library(lubridate)
data <- tibble(read.csv(file="household_power_consumption.txt", header=TRUE, sep=";"))
str(data)
data$Date <- dmy(data$Date)
data$Time <- hms(data$Time)
str(data)
data <- filter(data, Date > "2007-01-31" & Date < "2007-02-03") %>% mutate(Wochentag = weekdays(Date))
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
with(data, plot(x=Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering", xaxt='n', pch=2))
lines(data$Sub_metering_2, col="red")
lines(data$Sub_metering_3, col="blue")
legend("topright", lty=1 , col = c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex = 0.75)
axis(1, at=c(0, 1440, 2880), labels=c("Thu", "Fri", "Sat"))
dev.copy(png, file="plot3.png")
dev.off()