library(tidyverse)
library(lubridate)
data <- tibble(read.csv(file="household_power_consumption.txt", header=TRUE, sep=";"))
str(data)
data$Date <- dmy(data$Date)
data$Time <- hms(data$Time)
data <- filter(data, Date > "2007-01-31" & Date < "2007-02-03") %>% mutate(Wochentag = weekdays(Date))
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Voltage <- as.numeric(data$Voltage)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
data$Global_reactive_power <- as.numeric(data$Global_reactive_power)
str(data)

par(mfrow=c(2,2))
with(data, {
  plot(x=Global_active_power, type="l", col="black", xlab="", ylab="Global Active Power", xaxt='n', pch=2)
  axis(1, at=c(0, 1440, 2880), labels=c("Thu", "Fri", "Sat"))
  plot(x=Voltage, type="l", col="black", xlab="datetime", ylab="Voltage", xaxt='n', pch=2)
  axis(1, at=c(0, 1440, 2880), labels=c("Thu", "Fri", "Sat"))
  plot(x=Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering", xaxt='n', pch=2)
  lines(data$Sub_metering_2, col="red")
  lines(data$Sub_metering_3, col="blue")
  legend("topright", lty=1 , col = c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.33)
  axis(1, at=c(0, 1440, 2880), labels=c("Thu", "Fri", "Sat"))
  plot(x=Global_reactive_power, type="l", col="black", xlab="datetime", xaxt='n', pch=2)
  axis(1, at=c(0, 1440, 2880), labels=c("Thu", "Fri", "Sat"))
  })

dev.copy(png, file="plot4.png")
dev.off()

